import React from 'react';
import { useFinance } from '../context/FinanceContext';
import { Sparkles, Lightbulb, TrendingUp, HelpCircle, ShieldAlert } from 'lucide-react';

export const InsightsView: React.FC = () => {
  const { insights, transactions, budgets } = useFinance();

  const expenses = transactions.filter(t => t.type === 'expense');
  const totalExpense = expenses.reduce((sum, t) => sum + t.amount, 0);

  // Group by category for percentage breakdown
  const categoryTotals: Record<string, number> = {};
  expenses.forEach(t => {
    categoryTotals[t.category] = (categoryTotals[t.category] || 0) + t.amount;
  });

  const sortedCategories = Object.entries(categoryTotals).sort((a, b) => b[1] - a[1]);

  return (
    <div className="insights-view-container animate-fade-in">
      <h1 className="page-title">AI Spending Insights</h1>
      <p className="page-subtitle">Personalized observations and actionable tips generated by BudgetBuddy AI to improve your financial score.</p>

      <div className="dashboard-grid">
        {/* Detailed Insights list */}
        <div className="col-7 insights-left-col">
          <div className="glass-panel main-insights-panel">
            <div className="flex-align-center gap-2 mb-4">
              <Sparkles size={18} className="text-primary" />
              <h3 className="section-title">Active AI Alerts & Insights</h3>
            </div>

            <div className="insights-detailed-list">
              {insights.map((insight, idx) => (
                <div key={insight.id || idx} className="detailed-insight-card glass-panel">
                  <div className={`detailed-bullet ${insight.type}`}>
                    {insight.type === 'warning' ? <ShieldAlert size={18} /> : <Lightbulb size={18} />}
                  </div>
                  <div className="detailed-content">
                    <span className="insight-date">Date Generated: {new Date(insight.date).toLocaleDateString()}</span>
                    <p className="insight-message-text">{insight.message}</p>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>

        {/* Category Concentration & Breakdown */}
        <div className="col-5 glass-panel concentration-panel">
          <h3 className="section-title mb-4">Category Weight Analysis</h3>
          
          <div className="category-progress-list">
            {sortedCategories.length === 0 ? (
              <div className="empty-analysis">
                <span>No expense data to analyze yet.</span>
              </div>
            ) : (
              sortedCategories.map(([category, amt]) => {
                const percent = totalExpense > 0 ? Math.round((amt / totalExpense) * 100) : 0;
                return (
                  <div key={category} className="cat-analysis-row">
                    <div className="cat-analysis-meta">
                      <span className="cat-analysis-name">{category}</span>
                      <span className="cat-analysis-val">${amt.toFixed(2)} ({percent}%)</span>
                    </div>
                    <div className="cat-analysis-progress-track">
                      <div 
                        className="cat-analysis-progress-fill" 
                        style={{ width: `${percent}%` }}
                      ></div>
                    </div>
                  </div>
                );
              })
            )}
          </div>

          <div className="insights-footer-banner bg-success-glow mt-4">
            <TrendingUp size={16} className="text-success" />
            <span className="banner-text">
              Your overall food spending dropped <strong>12%</strong> compared to last week. Keep it up!
            </span>
          </div>
        </div>
      </div>

      <style>{`
        .insights-view-container {
          display: flex;
          flex-direction: column;
          gap: 0.5rem;
        }

        .insights-left-col {
          display: flex;
          flex-direction: column;
        }

        .main-insights-panel {
          padding: 1.5rem;
        }

        .insights-detailed-list {
          display: flex;
          flex-direction: column;
          gap: 1rem;
        }

        .detailed-insight-card {
          display: flex;
          gap: 1.25rem;
          padding: 1.25rem;
          background: rgba(24, 28, 41, 0.3);
          border-radius: 16px;
        }

        .detailed-bullet {
          width: 36px;
          height: 36px;
          border-radius: 10px;
          display: flex;
          align-items: center;
          justify-content: center;
          flex-shrink: 0;
        }

        .detailed-bullet.warning {
          background: var(--warning-glow);
          color: var(--warning);
        }

        .detailed-bullet.info {
          background: var(--info-glow);
          color: var(--info);
        }

        .detailed-bullet.success {
          background: var(--success-glow);
          color: var(--success);
        }

        .detailed-content {
          display: flex;
          flex-direction: column;
          gap: 0.35rem;
        }

        .insight-date {
          font-size: 0.7rem;
          color: var(--text-dim);
          font-weight: 600;
        }

        .insight-message-text {
          font-size: 0.85rem;
          color: var(--text-muted);
          line-height: 1.5;
          font-weight: 550;
        }

        .concentration-panel {
          padding: 1.5rem;
        }

        .category-progress-list {
          display: flex;
          flex-direction: column;
          gap: 1.25rem;
        }

        .cat-analysis-row {
          display: flex;
          flex-direction: column;
          gap: 0.4rem;
        }

        .cat-analysis-meta {
          display: flex;
          justify-content: space-between;
          font-size: 0.8rem;
          font-weight: 600;
        }

        .cat-analysis-name {
          color: var(--text-main);
        }

        .cat-analysis-val {
          color: var(--text-muted);
        }

        .cat-analysis-progress-track {
          height: 6px;
          background: rgba(255,255,255,0.04);
          border-radius: 3px;
          overflow: hidden;
        }

        .cat-analysis-progress-fill {
          height: 100%;
          background: linear-gradient(90deg, var(--primary) 0%, #c084fc 100%);
          border-radius: 3px;
        }

        .insights-footer-banner {
          display: flex;
          align-items: center;
          gap: 0.75rem;
          padding: 1rem;
          border-radius: 12px;
          border: 1px solid rgba(16, 185, 129, 0.15);
        }

        .banner-text {
          font-size: 0.775rem;
          color: var(--text-muted);
          font-weight: 550;
          line-height: 1.4;
        }

        .empty-analysis {
          padding: 2rem;
          text-align: center;
          color: var(--text-dim);
          font-size: 0.85rem;
        }
      `}</style>
    </div>
  );
};
